spring:
  datasource:
    url: jdbc:mysql://localhost:3306/msa
    username: root
    # password: password
    driver-class-name: com.mysql.jdbc.Driver
    
  jpa:
    generate-ddl: true
    show-sql: true